// Package docs serves the OpenAPI v2 spec generated by protoc-gen-openapiv2
// and a small Swagger UI page that loads it. The spec JSON is embedded into
// the binary so the resulting image has no external file dependencies.
package docs

import (
	_ "embed"
	"net/http"
)

//go:embed adsb.swagger.json
var swaggerJSON []byte

// SpecHandler serves the OpenAPI v2 spec as application/json.
func SpecHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Cache-Control", "no-store")
		_, _ = w.Write(swaggerJSON)
	})
}

// SwaggerUIHandler serves a single-page Swagger UI bundled from unpkg that
// points at the given spec URL (typically /openapi.json on the same host).
func SwaggerUIHandler(specURL string) http.Handler {
	page := `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>dump1090-adsblol — Swagger UI</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
  <style>body{margin:0}</style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js" crossorigin></script>
  <script>
    window.onload = () => {
      window.ui = SwaggerUIBundle({
        url: ` + jsString(specURL) + `,
        dom_id: '#swagger-ui',
        deepLinking: true,
        tryItOutEnabled: true,
      });
    };
  </script>
</body>
</html>`
	return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(page))
	})
}

// jsString returns the JSON-encoded form of s, suitable for inlining inside
// a <script> block as a JavaScript string literal.
func jsString(s string) string {
	var b []byte
	b = append(b, '"')
	for _, r := range s {
		switch r {
		case '"':
			b = append(b, '\\', '"')
		case '\\':
			b = append(b, '\\', '\\')
		case '\n':
			b = append(b, '\\', 'n')
		case '<':
			b = append(b, '\\', 'u', '0', '0', '3', 'c')
		default:
			if r < 0x20 {
				continue
			}
			b = append(b, []byte(string(r))...)
		}
	}
	b = append(b, '"')
	return string(b)
}
