// Package docs serves the OpenAPI v2 spec generated by protoc-gen-openapiv2
// and a single-page Swagger UI that loads it. The spec is embedded so the
// final binary needs no companion files
package docs

import (
	_ "embed"
	"net/http"
)

//go:embed adsb.swagger.json
var swaggerJSON []byte

func SpecHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Cache-Control", "no-store")
		_, _ = w.Write(swaggerJSON)
	})
}

// SwaggerUIHandler returns a tiny HTML page that pulls Swagger UI from unpkg
// and points it at specURL on the same host
func SwaggerUIHandler(specURL string) http.Handler {
	page := `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>dump1090-adsblol — Swagger UI</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
  <style>body{margin:0}</style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js" crossorigin></script>
  <script>
    window.onload = () => {
      window.ui = SwaggerUIBundle({
        url: ` + jsString(specURL) + `,
        dom_id: '#swagger-ui',
        deepLinking: true,
        tryItOutEnabled: true,
      });
    };
  </script>
</body>
</html>`
	return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(page))
	})
}

// jsString JSON-encodes s for safe inlining inside <script>. Notably escapes
// `<` so a stray "</script>" inside the URL can't close the surrounding tag
func jsString(s string) string {
	var b []byte
	b = append(b, '"')
	for _, r := range s {
		switch r {
		case '"':
			b = append(b, '\\', '"')
		case '\\':
			b = append(b, '\\', '\\')
		case '\n':
			b = append(b, '\\', 'n')
		case '<':
			b = append(b, '\\', 'u', '0', '0', '3', 'c')
		default:
			if r < 0x20 {
				continue
			}
			b = append(b, []byte(string(r))...)
		}
	}
	b = append(b, '"')
	return string(b)
}
